version: "3.8"
services:
    notice_bot:
        image: leontheprofess/notice_rabbitmq_bot
        restart: unless-stopped
        env_file: .env
        volumes:
          - logs:/bot/logs
volumes:
  logs: